
SELECT POID_DB,
       POID_ID0,
       POID_TYPE,
       POID_REV,
       {{ fnc_date_brm('CREATED_T') }} CREATED_T,
       {{ fnc_date_brm('MOD_T') }} MOD_T,
       READ_ACCESS,
       WRITE_ACCESS,
       ACCOUNT_OBJ_DB,
       ACCOUNT_OBJ_ID0,
       ACCOUNT_OBJ_TYPE,
       ACCOUNT_OBJ_REV,
       DESCR,
       END_T,
       NAME,
       OWN_MAX,
       OWN_MIN,
       PARTIAL,
       PERMITTED,
       PROVISIONING_TAG,
       PURCHASE_MAX,
       PURCHASE_MIN,
       START_T,
       TAX_SUPPLIER_ID_DB,
       TAX_SUPPLIER_ID_ID0,
       TAX_SUPPLIER_ID_TYPE,
       TAX_SUPPLIER_ID_REV,
       TYPE,
       PRIORITY,
       ZONEMAP_NAME,
       TAX_SUPPLIER,
       TAILORMADE,
       BASE_PRODUCT_OBJ_DB,
       BASE_PRODUCT_OBJ_ID0,
       BASE_PRODUCT_OBJ_TYPE,
       BASE_PRODUCT_OBJ_REV,
       CODE,
       LAST_UPD_GG
FROM {{ source('raw_brm','ttc_product_t') }}