select obj_id0,
       {{ fnc_translate("class") }}  class,
       class class_raw,
       {{ fnc_translate("subclass") }} subclass,
       subclass subclass_raw,
       digital_flag,
       exemp_from_collections,
       cve_razon_social,
       ind_sms,
       ind_unity,
       rpt_cuenta,
       company,
       start_t,
       ind_account_migrated,
       ind_valid_vat,
       previous_account_no,
       group_name,
       exemp_from_collections_t,
       last_upd_gg
from {{ source('raw_brm', 'ttc_cv_profile_account_t') }}       