select obj_id0,
       rec_id,
       address,
       canon_company,
       canon_country,
       city,
       company,
       contact_type,
       country,
       email_addr,
       first_canon,
       first_name,
       last_canon,
       last_name,
       middle_canon,
       middle_name,
       salutation,
       service_obj_db,
       service_obj_id0,
       service_obj_type,
       service_obj_rev,
       state,
       title,
       zip,
       geocode,
       taxpkg_type,
       last_upd_gg
from {{ source('raw_brm', 'ttc_account_nameinfo_t') }}       