SELECT POID_DB,
       POID_ID0,
       POID_TYPE,
       POID_REV,
       {{ fnc_date_brm('CREATED_T') }} CREATED_T,
       {{ fnc_date_brm('MOD_T') }} MOD_T,
       READ_ACCESS,
       WRITE_ACCESS,
       ACCOUNT_OBJ_DB,
       ACCOUNT_OBJ_ID0,
       ACCOUNT_OBJ_TYPE,
       ACCOUNT_OBJ_REV,
       INVOICE_OBJ_DB,
       INVOICE_OBJ_ID0,
       INVOICE_OBJ_TYPE,
       INVOICE_OBJ_REV,
       DUE_DOM,
       NAME,
       RELATIVE_DUE_T,
       ACH,
       PAYMENT_TERM,
       PAYMENT_OFFSET,
       INV_TYPE,
       LAST_UPD_GG

  FROM {{ source('raw_brm','ttc_payinfo_t') }}