select poid_db,
       poid_id0,
       poid_type,
       poid_rev,
       {{ fnc_date_brm('CREATED_T') }} created_t,
       created_t created_t_raw,
       {{ fnc_date_brm('MOD_T') }} mod_t,
       mod_t mod_t_raw,
       read_access,
       write_access,
       config_scenario_obj_db,
       config_scenario_obj_id0,
       config_scenario_obj_type,
       config_scenario_obj_rev,
       account_obj_db,
       account_obj_id0,
       account_obj_type,
       account_obj_rev,
       agent_obj_db,
       agent_obj_id0,
       agent_obj_type,
       agent_obj_rev,
       overdue_t,
       overdue_amount,
       {{ fnc_date_brm('ENTRY_T') }} entry_t,
       entry_t entry_t_raw,
       entry_amount,
       exit_t,
       exit_amount,
       reason,
       billinfo_obj_db,
       billinfo_obj_id0,
       billinfo_obj_type,
       billinfo_obj_rev,
       last_upd_gg,
       external_user
  from {{ source('raw_brm','ttc_collections_scenario_t') }}
 where 1 = 1