SELECT ROW_ID,
       CREATED,
       CREATED_BY,
       LAST_UPD,
       LAST_UPD_BY,
       DCKING_NUM,
       MODIFICATION_NUM,
       CONFLICT_ID,
       PAR_ROW_ID,
       BU_ID,
       LANG_ID,
       NAME,
       RPLCTN_LVL_CD,
       TYPE,
       VAL,
       ACTIVE_FLG,
       MODIFIABLE_FLG,
       MULTI_LINGUAL_FLG,
       ORDER_BY,
       TARGET_HIGH,
       TARGET_LOW,
       TRANSLATE_FLG,
       WEIGHTING_FACTOR,
       BITMAP_ID,
       CODE,
       DESC_TEXT,
       HIGH,
       INTEGRATION_ID,
       LOW,
       SUB_TYPE,
       DB_LAST_UPD,
       DB_LAST_UPD_SRC,
       DFLT_LIC_FLG,
       MLTORG_DISALW_FLG,
       REQD_LIC_FLG,
       X_TT_READ_ONLY_FLG,
       WS_ID,
       WS_INACTIVE_FLG,
       WS_MAX_VER,
       WS_MIN_VER,
       WS_SRC_ID,
       LAST_UPD_GG

  FROM {{ source('raw_crm','ttc_s_lst_of_val') }} 
 WHERE 1 = 1                